name: spell-check
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: .github/workflows/typos-config.toml
jobs:
  check:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Check spelling
        uses: crate-ci/typos@v1.41.0
        with:
          config: ${{ inputs.config }}
